version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_django
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    environment:
      DB_ENGINE: ${DB_ENGINE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile_celery
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    depends_on:
      - redis
      - web
    volumes:
      - ./api:/app/api

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"

  redis:
    image: redis:alpine

volumes:
  postgres_data:
